### ISSUE TITLE
Why storing PDFs in working folder?

### ISSUE THREAD

**Issue by jlivingood** [bitag-twg/bitag2.0#13]
Q for @mjtooley as to why we'd store PDFs in the GH folder - could confuse people and they might try to comment on the PDF rather than work directly with the markdown doc.

**Comment by mjtooley** [comment]
Just an artifact of when I generated PDF.  My machine pushed the PDF that got generated in the folder.

Matt Tooley

NCTA – The Internet & Television Association
o (202) 222-2479 ● m (202) 361-5932 ● mtooley@ncta.com<mailto:mtooley@ncta.com>

Discover all that we do at ncta.com
