### ISSUE TITLE
Section 2 subsection ordering

### ISSUE THREAD

**Issue by jlivingood** [bitag-twg/bitag2.0#16]
I would suggest we take a layered approach (inside-out) to the sub-section ordering. 

Thus something like:
1 - User Devices (noting new purchases, replacement/upgrade, devices brought from work/school - can find refs to device sales/scarcity etc)
2 - The Home Network (noting WiFi issues & buffer bloat experiences)
3 - The ISP Access Networks
4 - Transit Networks
5 - Internet Exchange Points
6 - Interconnection (SFI and paid)
7 - Content Delivery Networks (e.g. Akamai, etc.)
8 - Cloud Providers / Backend Infrastructure (e.g. AWS, Azure, etc.)
9 - End User Application Providers (e.g. Netflix, Zoom, Webex, Google, etc.) - would cover both the client app side (e.g. zoom security upgrades & call of duty content updates) as well as server-side scaling/demand

**Comment by jlivingood** [comment]
FYI @mjtooley this may be a good discussion item for the 1st call

**Comment by mjtooley** [comment]
I think that makes sense, basically tell the story starting with the end-user and working our way across the cloud.

**Comment by jlivingood** [comment]
Created a PR for this https://github.com/bitag-twg/bitag2.0/pull/20
